### ISSUE TITLE
Unit of grid resolution

### ISSUE THREAD

**Issue by bakcsa83** [mocnik-science/geogrid#7]
Reading the readme and the code it's not immediately obvious how should one interpret the `resolution` variable used at many places in the code.

Would it be possible to elaborate on it?

I found a table in [this](https://www.discreteglobalgrids.org/wp-content/uploads/2019/05/dggridManualV64.pdf) paper  (Appendix D, page 26) that nicely summarizes the properties of each possible resolution.
Is that table correct? If so, would it be possible to add something similar to the readme?

**Comment by mocnik-science** [comment]
The paper you provide a reference to refers to another implementation.  As far as I know, the other implementation handles the parameter `resolution` in the same way as `geogrid` does.

I advise to read the following paper as it discusses the general context of this library:
https://www.tandfonline.com/doi/full/10.1080/15230406.2018.1455157
Adding the content of this article (including the corresponding table) is not possible due to copyright issues, nor does it make sense – this is why a properly typesetted article exists.  If you do not have access to the article, please let me know your email address.

**Comment by bakcsa83** [comment]
Thanks for the response.
Do you get some money from www.tandfonline.com if I pay for the article? (I've no idea how it works)

**Comment by mocnik-science** [comment]
You are welcome.

No, I do not receive any money from Tailor & Francis.  The money paid to academic publishers is used to typeset the article, etc.  Universities tend to have subscriptions to these journals, such that you can access them for free.
